name: Create new talos ISO with DRBD
on:
  release:
    types: [created]
# on: push
permissions:
  contents: write
  discussions: write
# env:
#   DRBD_IMAGE_VERSION: ${{ github.event.release.tag_name }}
  # DRBD_IMAGE_VERSION: '9.2.4-v1.5.1'
jobs:
  Build:
    name: Build new image
    runs-on: ubuntu-latest
    steps:
      # - name: Set Talos Version
      #   shell: pwsh
      #   id: talos
      #   run: |
      #     $talos_ver = '${{ env.DRBD_IMAGE_VERSION }}'.Split('-')[-1]
      #     "TALOS_VERSION=$talos_ver" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build new image
        shell: pwsh
        run: |
          $drbd_image_version: ${{ github.event.release.tag_name }}
          $talos_version = $drbd_image_version.Split('-')[-1]
          docker run --rm -t -v $PWD/_out:/out -v /dev:/dev --privileged ghcr.io/siderolabs/imager:$talos_version iso --system-extension-image ghcr.io/siderolabs/drbd:$drbd_image_version
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./_out/metal-amd64.iso

            
