name: Create new talos ISO with DRBD
on:
  release:
    types: [created]
jobs:
  Build:
    name: Build new image
    runs-on: ubuntu-latest
    steps:
      - name: Build new image#
        run: docker run --rm -t -v $PWD/_out:/out -v /dev:/dev --privileged ghcr.io/siderolabs/imager:v1.5.0 iso --system-extension-image ghcr.io/siderolabs/drbd:9.2.4-v1.5.0
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: _out/metal-amd64.iso
          asset_name: metal-amd64.iso
          asset_content_type: application/octet-stream
            
